apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-nodeport
  namespace: staging
spec:
  selector:
    app: ecommerce-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010