apiVersion: v1
kind: Service
metadata:
  name: order-service-nodeport
  namespace: staging
spec:
  selector:
    app: order-service
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30012