apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: dev
  labels:
    app: database
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: eronan22/database:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: database-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - admin
                - -d
                - ecommerce
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - admin
                - -d
                - ecommerce
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pvc